### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by bertraj** [WSDOT/wsdot-website#143]
Import our custom 404 page.

**Comment by waynedyck** [comment]
There are several ways we can do this. At first I was concerned that if we set the 404 as a piece of content then it as the potential to be one of our top most accessed pages; apparently we already have this issue on our existing site. Perhaps not an issue.

The other issue is whether the 404 page will actually be served from Drupal or from our existing web servers because we are using the NetScaler to redirect only those links which are in Drupal.

**Comment by waynedyck** [comment]
This solution posted on [drupal.stackexchange.com](http://drupal.stackexchange.com/a/146849) was what was used. The original post goes back to a discussion on drupal.org on [how to specify 403 and 404 error pages](https://www.drupal.org/node/15366#comment-7218780).
