### ISSUE TITLE
YouTube player

### ISSUE THREAD

**Issue by muffr** [WSDOT/wsdot-website#229]
Fetches YouTube thumbnail, displays thumbnail and play button and creates iframe for embedded YouTube player when play button is clicked.

**Comment by waynedyck** [comment]
Closed with commit 5862f55d503855d92c987acb9ebab512da309c64

**Comment by waynedyck** [comment]
The only outstanding issue I see with it is the width of the player when there is little to no text on the page. Because the width of the player is percentage based and responsive, when there are only a few words on the page the surrounding div is very small and therefore the player itself is small.

I would classify this as an edge case, because we are not likely to have just a video on a page with no explanation, however, it's still something to be aware of.
